language: objective-c

before_install:
  - gem install cocoapods
  - brew update
  - if brew outdated | grep -qx xctool; then brew upgrade xctool; fi

xcode_workspace: TravisTest.xcworkspace
xcode_scheme: TravisTest
xcode_sdk: iphonesimulator
