language: objective-c

before_install:
  - gem install cocoapods
  - brew update
  - if brew outdated | grep -qx xctool; then brew upgrade xctool; fi

xcode_workspace: TravisTest.xcworkspace
xcode_sdk: iphonesimulator

notifications:
  email:
    recipients:
    - babb2@hotmail.com
    - jak@microsoft.com
    on_success: never
    on_failure: always
  
