language: objective-c
before_install:
- gem install cocoapods
- brew update
- if brew outdated | grep -qx xctool; then brew upgrade xctool; fi
script:
- xctool -workspace TravisTest.xcworkspace -scheme TravisTest -sdk iphonesimulator
notifications:
  email:
    recipients:
    - jak@microsoft.com
    on_success: never
    on_failure: always
  slack:
    secure: Oo3ZtjLWGUtuNklrYtXDXnekEQFicmWqQOA9tzm4XbNSGoYJL4qIVr9UiV1dLsE3+Xg8h3XyPGg5o2KXxQxH/4/psRErZ1+9J25lWnd4ueM3kF4lqwAECg+WRetLFeMYzYnhLYkSYqkkkLxwMpqXZxF7yNN/9/JWPKL2g39pRk1PyQt9+UPrJuPoJGzUCU1c/kBRUMu67cLPDLhp+9VXHIT88Mr5GDRzeHBWJqDzr4ej8hR510ifDvcnifVfsn5sMg2cOkYh/BDdKqzFFCCGDcKlxSHqnd1/EzfFgFwlgAoziPvm3Ulw9j6TTSHx2qq8yHBMGZaaNSjDfwMYB72/5lZFvoMahbPnuSse0b6o4YySmN62Hyskbd2G3+RjQ1PJWvS00AC5WIE8OhAMxAPSarWu05H0m2NX9j9IO/hI8bcE7aLgT+rvsTSFmsdmAYwRine5UI8IrHk94qdezvCxkQpgzzk+uyVL/dy4Aw01wgR4VOpspq1boYrzDRMr/MZk1hMJFF02GobVa/qmOoswIx9jiDrWR6wiumgWQxgoPK/IZdywQH+cuG7IUFbJnNGY/XHKV5vsLwxvzgzWWT/8c0EIMm7KVbshBC64zO8GGkZpKFeZw42T61ObpUHxss4LfyzmSybNtON3NFlY1HhMub3iFokSftzEuCaNbdVQAF4=
    on_success: never
    on_failure: always
    
